### ISSUE TITLE
Tutorial code does not function for v5

### ISSUE THREAD

**Issue by mcquiggd** [elastic/elasticsearch-net-example#10] opened 2017-03-17 13:43 UTC
Just a heads up, **not** a complaint - I appreciate all the work you are doing, but there are so many issues with the Tutorial that it is perhaps best to deprecate it, I know it carries a warning, but it simply does not work... it can lead to people spending a lot of time trying to find fixes that will never work rather than learning, and understanding.

The branch version 5 did not seem to work (code as download, additions from the Tutorial), potentially due to different versions being used for the tutorial. Some functions on the Client are now properties, etc.

The branch version 5 `complete `did not work (code as download, no changes), generating errors with autocomplete (but, they may have been due to attempting to follow along with the Tutorial, and creating multiple indexes that confused the codebase).

**Now, the good news!**

The branch version 5- `deploy `does seem to work on a fresh install (code as downloaded, no changes), and seem to be more feature complete in terms of the UI and demonstration of Elasticsearch`s capabilities. I would point people to this.

I would recommend reading the Tutorial for understanding concepts, by working through the code for version 5 - `deploy  `for a working example.

Not a complaint, as I say, more of a heads up for people following along - the Tutorial, and the sample code is out of step. If I can find time I will make a PR for a few issues I noticed over the last two days (e.g. setup tricks, correcting the syntax in the Tutorial, slightly rearranging it).

**Comment by russcam** [comment] 2017-03-17 21:53
Thank you for the feedback @mcquiggd, most appreciated!

Sorry to hear that the `5.x` and `5.x-codecomplete` branches did not work, they should be in a state where they do. Do you have a list of feedback that would help us resolve this issue or opening a PR to fix? The `5.x-deploy` branch is a little different in how Nancy is hosted (in IIS as opposed to self-hosted), so that it can be happily deployed to Azure.

Our plan is to update this example repository to use ASP.NET Core as well as update the styling. We see this as a useful resource so are keen to keep it up to date.

**Comment by mcquiggd** [comment] 2017-03-18 02:35
@russcam 

I will try to go through it again this weekend, and make notes where it is not in sync, or simply not working...

I will also retry `5.x-codecomplete` with a clean Elasticsearch setup (no existing Indexes), which might help.

And ASP.Net Core - two thumbs up! Exactly what I wanted to hear. Will try to assist... `

**Comment by christofur** [comment] 2017-05-17 15:49
@mcquiggd 

Hey, I'm going through the 5.x branch tutorial now, and things seem to work fine for me, I'm using a clean 5.4.0 Elasticsearch instance. If there's anything in particular you're having a problem with, I'd be happy to try and help.

**Comment by Mpdreamz** [comment] 2017-06-04 03:20
Closing this for now since we can't reproduce. Looking forward to your notes @mcquiggd in the future, 👍

**Closed by Mpdreamz** 2017-06-04 03:20 UTC
